# Generated by Django 2.2 on 2021-08-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvenConsumption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_info', models.DateField(blank=True, null=True)),
                ('time_info', models.TimeField(blank=True, null=True)),
                ('conv_cons', models.TimeField(blank=True, null=True)),
                ('unconv_cons', models.FloatField(null=True)),
                ('conv_cons_al', models.FloatField(null=True)),
                ('unconv_cons_al', models.FloatField(null=True)),
                ('t_min', models.FloatField(null=True)),
                ('t_max', models.FloatField(null=True)),
                ('t_avg', models.FloatField(null=True)),
                ('p_min', models.FloatField(null=True)),
                ('p_max', models.FloatField(null=True)),
                ('p_avg', models.FloatField(null=True)),
                ('qu_min', models.FloatField(null=True)),
                ('qu_max', models.FloatField(null=True)),
                ('qc_min', models.FloatField(null=True)),
                ('qc_max', models.FloatField(null=True)),
                ('converted_index', models.FloatField(null=True)),
                ('unconverted_index', models.FloatField(null=True)),
                ('converted_counter', models.FloatField(null=True)),
                ('unconverted_counter', models.FloatField(null=True)),
                ('p2_min', models.FloatField(null=True)),
                ('p2_max', models.FloatField(null=True)),
                ('p2_moy', models.FloatField(null=True)),
            ],
        ),
    ]
