# Generated by Django 2.2 on 2021-08-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210817_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovenconsumption',
            name='conv_cons',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ovenconsumption',
            name='conv_cons_al',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ovenconsumption',
            name='unconv_cons',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ovenconsumption',
            name='unconv_cons_al',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
