# Generated by Django 2.2 on 2021-08-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210817_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovenconsumption',
            name='time_info',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
