# Generated by Django 2.2 on 2021-08-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210817_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovenconsumption',
            name='conv_cons',
            field=models.TimeField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ovenconsumption',
            name='time_info',
            field=models.TimeField(max_length=100, null=True),
        ),
    ]
