# Generated by Django 2.2 on 2021-09-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210817_0522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chip',
            new_name='ChipInfo',
        ),
    ]
