# Generated by Django 2.2 on 2021-09-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210909_1408'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChipComposition',
            new_name='Chip',
        ),
    ]
