# Generated by Django 2.2 on 2021-09-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210909_1511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alloy',
            new_name='AlloyingElement',
        ),
    ]
