# Generated by Django 2.2 on 2021-09-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20210910_0705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingot',
            new_name='AlloyStandard',
        ),
    ]
