# Generated by Django 2.2 on 2021-09-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20210910_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='alloystandard',
            name='security_coef_max',
            field=models.FloatField(default='0.01', null=True),
        ),
        migrations.AddField(
            model_name='alloystandard',
            name='security_coef_min',
            field=models.FloatField(default='0.01', null=True),
        ),
        migrations.AddField(
            model_name='alloystandard',
            name='weight_kg',
            field=models.FloatField(default='0', null=True),
        ),
    ]
