# Generated by Django 2.2 on 2021-09-29 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20210920_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alloyingelement',
            old_name='min_price_kg',
            new_name='min_weight_kg',
        ),
        migrations.RenameField(
            model_name='chip',
            old_name='min_price_kg',
            new_name='min_weight_kg',
        ),
        migrations.RenameField(
            model_name='scrap',
            old_name='min_price_kg',
            new_name='min_weight_kg',
        ),
    ]
