# Generated by Django 2.2 on 2022-02-02 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_csvfiles_csvfilesdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfilesdata',
            name='csvFile',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='dashboard.csvFiles'),
        ),
        migrations.AlterField(
            model_name='csvfilesdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
