# Generated by Django 2.2 on 2022-02-02 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20220202_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfilesdata',
            name='csvFile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.csvFiles'),
        ),
    ]
