# Generated by Django 2.2 on 2022-02-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20220204_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfilesdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
