# Generated by Django 2.2 on 2022-02-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20220206_0718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvfilesdata',
            old_name='plunger_position',
            new_name='PlungerPosition',
        ),
    ]
