# Generated by Django 2.2 on 2022-02-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20220211_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfilesdata',
            name='CounterPressure',
            field=models.FloatField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='csvfilesdata',
            name='EffectivePressure',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csvfilesdata',
            name='HeadPressure',
            field=models.FloatField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='csvfilesdata',
            name='PlungerPosition',
            field=models.FloatField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='csvfilesdata',
            name='Pressure1',
            field=models.FloatField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='csvfilesdata',
            name='Pressure2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csvfilesdata',
            name='Temperature1',
            field=models.FloatField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='csvfilesdata',
            name='Velocity',
            field=models.FloatField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='csvfilesdata',
            name='Voltage1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csvfilesdata',
            name='Voltage2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csvfilesdata',
            name='Voltage3',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csvfilesdata',
            name='Voltage4',
            field=models.FloatField(default=0, null=True),
        ),
    ]
