# Generated by Django 2.2 on 2022-02-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20220211_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfilesdata',
            name='EffectivePressure',
            field=models.FloatField(default=0),
        ),
    ]
