# Generated by Django 2.2 on 2022-02-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20220211_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfilesdata',
            name='Voltage5',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
    ]
