# Generated by Django 2.2 on 2022-02-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20220211_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfilesdata',
            name='Voltage5',
            field=models.FloatField(default=0.0),
        ),
    ]
