# Generated by Django 2.2 on 2022-02-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_auto_20220211_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfilesdata',
            name='Voltage5',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
