# Generated by Django 2.2 on 2022-02-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20220211_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfilesdata',
            name='Voltage4',
            field=models.FloatField(default='0.1', null=True),
        ),
    ]
