# Generated by Django 2.2 on 2022-06-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_auto_20220211_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfiles',
            name='anomaly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='csvfiles',
            name='quality',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
