# Generated by Django 2.2 on 2022-07-06 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_auto_20220623_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfilesdata',
            name='csvFile',
        ),
        migrations.DeleteModel(
            name='csvFiles',
        ),
        migrations.DeleteModel(
            name='csvFilesData',
        ),
    ]
